codewar/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from codewar import views


app_name = 'codewar'


urlpatterns = [
    path(r'', views.HomeView.as_view(), name='home'),
    path(r'history/', views.HistoryView.as_view(), name='history'),
    path(r'editor/<int:pk>/', views.CodeEditorView.as_view(), name='editor'),
    path(r'attempt/<int:problem_id>/', views.process_attempt, name='attempt'),
    path(r'howto/', views.HowToView.as_view(), name='howto'),
    path(
        r'topten/',
        cache_page(5)(views.TopTenView.as_view()),
        name='topten'
    ),
    path(r'feedback/', views.feedback, name='feedback'),
    path(r'me/', views.ProfileView.as_view(), name='me'),
    path(r'profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path(
        r'showsolution/<int:problem_id>/',
        views.show_solution,
        name='showsolution'
    ),
]

contest/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static
from filebrowser.sites import site

from codewar import views

urlpatterns = [
    path(r'admin/tinymce/', include('tinymce.urls')),
    path(r'admin/filebrowser/', site.urls),
    path(r'admin/', admin.site.urls),
    path(r'login', views.LoginView.as_view(), name='login'),
    path(r'logout', views.user_logout, name='logout'),
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'event', views.EventView.as_view(), name='event'),
    path(
        r'event/<int:pk>/',
        views.EventProcessView.as_view(),
        name='event_detail'
    ),
    path(
        r'event/<int:pk>/leave',
        views.leave_event,
        name='event_leave'
    ),
    path(r'register', views.RegisterView.as_view(), name='register'),
    # path(r'forgotpassword', views.forgot_password, name='forgotpassword'),
    # path(
    #     r'passwordresetconfirm/<str:uidb64>/<str:token>',
    #     views.passwordresetconfirm,
    #     name='password-reset'
    # ),
    path(r'codechallenges/', include('codewar.urls')),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import re_path

codewar/models.py
from django.contrib.auth.models import Group
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.conf import settings

from tinymce.models import HTMLField

from codewar.enums import (EventType, EventStatus,
    ProblemType, ProblemCategory, MarkedScore,
    AttemptLanguage, AttemptStatus)
import codewar.utils as utils


# Create your models here.
class Event(models.Model):
    name = models.CharField(
        max_length=64, blank=False, editable=True)
    prefix = models.CharField(
        max_length=64, blank=True, null=True, editable=True)
    time_start = models.DateTimeField()
    time_end = models.DateTimeField()
    type = models.IntegerField(
        choices=EventType.choices, default=EventType.CODE_CHALLENGE)
    # status should be property
    status = models.IntegerField(
        choices=EventStatus.choices, default=EventStatus.INACTIVE)
    is_teamwork = models.BooleanField(
        _('Teamwork'), default=False, editable=True)
    is_leaderboard = models.BooleanField(
        _('Leaderboard'), default=True, editable=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_time_start(self):
        return timezone.make_naive(
            self.time_start
        ).strftime('%d-%m-%Y %H:%M:%S %p')

    def get_time_end(self):
        return timezone.make_naive(
            self.time_end
        ).strftime('%d-%m-%Y %H:%M:%S %p')

    def get_current_status(self):
        now = timezone.now()
        if self.time_start <= now and self.time_end > now:
            return EventStatus.ACTIVE
        elif self.time_end <= now:
            return EventStatus.FINISHED
        else:
            return EventStatus.INACTIVE

    def get_prefix(self):
        return self.prefix or ''


class Problem(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name='problem',
        blank=True,
        null=True,
        editable=False
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='problem',
        null=True
    )
    type = models.IntegerField(
        choices=ProblemType.choices,
        default=ProblemType.CODE
    )
    title = models.CharField(max_length=255)
    score = models.IntegerField(default=0)
    required_score = models.IntegerField(default=0)
    category = models.IntegerField(
        choices=ProblemCategory.choices,
        default=ProblemCategory.CPP
    )
    published = models.BooleanField(default=False, editable=False)
    max_attempts = models.IntegerField(default=0)
    max_wrong = models.IntegerField(default=0)
    penalty_score = models.IntegerField(default=0)
    solution_shown = models.BooleanField(default=False, editable=False)
    content = HTMLField()
    solution = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    binary_server = models.TextField(editable=True, blank=True, null=True)

    def __str__(self):
        return self.title

    def count_testcase(self):
        return self.testcase.count()

    def is_published(self, is_forced=False):
        return is_forced or self.is_published

    def _is_solve_allowed(self, score):
        return (self.required_score <= score and
            self.published and
            not self.solution_shown)

    def is_solve_allowed(self, score, is_forced=False):
        if is_forced or self._is_solve_allowed(score):
            return True
        return False

    def _is_solved(self, participant):
            return Attempt.objects.filter(
                event=self.event,
                problem=self,
                status=0,
                participant=utils.get_participant_id(
                    participant,
                    self.event.is_teamwork
                )
            )

    def is_solved(self, participant, is_forced=False):
        return None if is_forced else self._is_solved(participant)

    def list_solved(self):
        return Attempt.objects.filter(
            event=self.event,
            problem=self,
            status=AttemptStatus.FINISHED
        )

    def get_content(self, score, is_forced=False):
        if is_forced:
            return self.content

        if self.required_score > 0:
            return self.content if self.required_score <= score else \
                "Need more score to unlock it!"
        return self.content

    def get_real_score(self):
        count = Attempt.objects.filter(
            event=self.event,
            problem=self,
            status=AttemptStatus.FINISHED
        ).count()
        score = self.score - int(self.penalty_score) * count
        return self.penalty_score if score < self.penalty_score else score


class TestCase(models.Model):
    problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name='testcase'
    )
    input = models.TextField(null=True, blank=True)
    output = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.input[:80]


class Attempt(models.Model):
    problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name='attempt'
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='attempt',
        null=True, editable=True
    )
    participant = models.IntegerField(
        null=True, blank=True, editable=False
    )
    content = models.TextField()
    language = models.CharField(
        max_length=8,
        choices=AttemptLanguage.choices,
        default=AttemptLanguage.CPP,
        null=True, blank=True
    )
    task = models.CharField(max_length=128, null=True, blank=True)
    status = models.IntegerField(
        choices=AttemptStatus.choices,
        null=True, blank=True
    )
    result = models.TextField(
        null=True, blank=True)
    marked_score = models.IntegerField(
        choices=MarkedScore.choices,
        default=MarkedScore.NO
    )
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content[:80]

    def get_participant_name(self):
        return utils.get_participant(
            self.participant,
            self.event.is_teamwork
        )
    get_participant_name.short_description = 'Participant'


class Score(models.Model):
    participant = models.IntegerField(null=True, blank=True)
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='event'
    )
    score = models.IntegerField(null=True, blank=True, default=0)
    modified_at = models.DateTimeField("Last modify", auto_now=True)

    def __str__(self):
        return str(self.score)

    # TODO Change the function name
    def get_participant_name(self):
        return utils.get_participant(
            self.participant,
            self.event.is_teamwork
        )
    get_participant_name.short_description = "ID"

    def get_full_name(self):
        return utils.get_participant_fullname(
            self.participant,
            self.event.is_teamwork
        )
    get_full_name.short_description = "Name"

    def add_score(self, score):
        self.score += score


class GroupEvent(models.Model):
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='group_event'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name='group_event'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_groupname(self):
        return utils.get_groupname_from_id(self.group.pk)
    get_groupname.short_description = 'Name'


class UserEvent(models.Model):
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name='user_event'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='user_event'
    )
    is_active = models.BooleanField(default=False)
    is_teamwork = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_username(self):
        return utils.get_user_from_id(self.user.pk)
    get_username.short_description = 'Name'

codewar/templates/codewar/code-editor.html
{% load static %}
<div class="animated fadeIn">
  <div class="row">
    <div class="col-md-12 col-lg-8">
      <div class="border-primary">
        <ul class="nav nav-tabs border-primary" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#codeeditor" role="tab" aria-controls="home" aria-expanded="true">
              <i class="icon-doc"></i>
              Code Editor
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#problem" role="tab" aria-expanded="false">
                <i class="icon-question"></i>
                Problem
              </a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="codeeditor" role="tabpanel" aria-expanded="true">
            <div class="row">
              <div class="form-group col-sm-4">
                <select class="form-control" id="language" onchange="changeLanguage(this)">
                  <option value="cpp">C++ (Gcc 8.3)</option>
                  <option value="java">Java (version 11)</option>
                  <option value="js">NodeJS (version 10.16)</option>
                </select>
              </div>
              <div class="form-group col-sm-8">
                <a class="btn btn-outline-info float-right" style="margin-left: 10px;" href="#" data-target="#popupinfo" data-toggle="modal"><i class="icon-info"></i></a>
                <div class="input-group-btn float-right">
                <a class="btn btn-primary" href="#" onclick="compileAndRun(this)" action="compile_run"><i class="icon-rocket"></i>
                  Run
                </a>
                </div>
              </div>
            </div>
            <div id="editor" style="min-height: 500px;margin-left: -15px"></div>
          </div>
          <div class="tab-pane" id="problem" role="tabpanel" aria-expanded="false">
            <h5>{{ problem.title }}</h5>
            <hr />
            {{ problem.content|safe  }}
            <input type="hidden" id="problem_id" value="{{ problem.id }}">
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12 col-lg-4">
      <div class="border-primary">
        <ul class="nav nav-tabs border-primary" role="tablist">
          <li class="nav-item ">
            <a class="nav-link active" data-toggle="tab" href="#iframeResult" role="tab" aria-expanded="true">
              <i class="icon-fire"></i>
              Console
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#custominput" role="tab" aria-expanded="false">
              <i class="icon-question"></i>
              Custom Input
            </a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="iframeResult" role="tabpanel" aria-expanded="true">
            Click <b><i class="icon-rocket"></i> Run</b>
          </div>
          <div class="tab-pane" id="custominput" role="tabpanel" aria-expanded="true">
            <textarea id="cinput" name="custtominput" rows="2"
              class="form-control" placeholder="Your input goes here">{{ problem.testcase.first.input }}</textarea>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="popupinfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  {% include "modal/code-editor-help.html"%}
</div>

<script>
  ace.require("ace/ext/language_tools");
  var editor = ace.edit("editor");
  editor.setTheme("ace/theme/sqlserver");
  editor.setOptions({
    enableBasicAutocompletion: true,
    enableSnippets: true,
    enableLiveAutocompletion: true
  });

  lastCode = getCookie('problem-{{ problem.id }}')

  if (lastCode === null) {
    editor.getSession().setMode("ace/mode/c_cpp");
    editor.setValue(
`#include <iostream>

using namespace std;

int main()
{
    // your code goes here
    int val;
    cin >> val;
    cout << val;
    return 0;
}`
    );
  } else {
    lastSession = JSON.parse(lastCode);
    editor.getSession().setMode(lastSession.mode);
    editor.setValue(lastSession.lastCode);
  }

  function saveCode(){
    key = 'problem-{{ problem.id }}';
    mode = editor.getSession().getMode().$id;
    lastCode = editor.getValue();
    data = JSON.stringify({"mode": mode, "lastcode": lastCode});
    setCookie(key, data, 1);
  }

  autoSave = setInterval(function() { saveCode(); }, 60000);

  function changeLanguage(arg) {
    if (arg.value == 'cpp') {
      editor.getSession().setMode("ace/mode/c_cpp");
      editor.setValue(
`#include <iostream>

using namespace std;

int main()
{
    // your code goes here
    int val;
    cin >> val;
    cout << val;
    return 0;
}`
      );
    } else if (arg.value == 'js') {
      editor.getSession().setMode("ace/mode/javascript");
      editor.setValue(
`const readline = require('readline');

const main = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

main.on('line', answer => {
    // your code goes here
    process.stdout.write('true');
    main.close();
});`
      );
    } else {
      editor.getSession().setMode("ace/mode/java");
      editor.setValue(
`import java.util.*;
import java.lang.*;
import java.io.*;

// Don't replace this class name with another!
public class CodeChallenges
{
    public static void main(String[] args)
    {
        // your code goes here
        Scanner s = new Scanner(System.in);
        int val = s.nextInt();
        System.out.print(val);
    }
}`
      );
    }
  }
</script>

codewar/templates/codewar/event.html
{% load static eventtags %}
<div name="card" class="card border-secondary">
  <a data-toggle="collapse" href="#" data-target="#collapse">
    <div class="card-header card-header" ><i class="fa fa-search fa-lg" style="color: #00a9dc"></i>
      <b style="color: #00a9dc">Filter Advance</b>
    </div>
  </a>
  <div class="card-body collapse" id="collapse">
    <div class="row">
      <div class="form-group-filter col-sm-6">
          <input class="form-control" id="myInput" type="text" placeholder="Search.." readOnly>
      </div>
    </div>
  </div>
</div>
<div class="animated fadeIn">
  <div class="row">
    <div class="col-md-12">
      {% for event in events %}
        {{ event|get_card:user|safe }}
      {% endfor %}
    </div>
  </div>
</div>

<script>
  var eventList = [];
  {% for event in events %}
    {% if event.get_current_status != 0 %}
      eventList.push({
        id: null,
        {% if event.get_current_status == 2 %}
            date: {{ event.time_start.timestamp }},
        {% else %}
            date: {{ event.time_end.timestamp }},
        {% endif %}
        target: document.getElementById("countdown-{{ event.pk }}"),
      });
    {% endif %}
  {% endfor %}

  eventList.forEach(function(element) {
    element.id = setInterval(function () {
      getCountdown(element.date, element.target);
    }, 1000);
    {% comment %}
      console.log("Create Interval Countdown :: " + element.id);
    {% endcomment %}
  });
</script>

codewar/templates/codewar/feedback.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Feedback</title>
    <style>
      h1 { color: #333333; font-family: 'Bitter', serif; font-size: 50px; font-weight: normal; line-height: 54px; margin: 0 0 54px; }
      p { color: #333333; font-family: Georgia, serif; font-size: 18px; line-height: 28px; margin: 0 0 28px; }
      p:first-of-type { font-size: 26px; line-height: 36px; margin: 0 0 28px; }
      a { color: #c73036; font-family: Georgia, serif; text-decoration: underline; }
      a:hover { color: #333333; text-decoration: underline; }
      .author { color: #8d8d8d; font-family: Georgia, serif; font-style: italic; font-size: 14px; margin-bottom: 28px; }
      .author a { color: #c73036; font-family: "Helvetica Neue", sans-serif; font-weight: bold; text-decoration: none; text-transform: uppercase; }
    </style>
  </head>
  <body>
    <div class="content1">
      <p >%title%</p>
      <p class="author">This feedback is from %username%</p>
      <p>%content%</p>
      <div class="line"></div>
      <p class="author">Contact <a href="mailto:%username%" class="author">%username%</a></p>
    </div>
  </body>
</html>

codewar/templates/codewar/history.html
{% load static codewartags %}
<div class="animated fadeIn">
  <div class="row">
    <div class="col-lg-12">
      <div class="card border-primary">
        <div class="card-header">
          <i class="fa fa-history"></i>
          <b>History</b>
        </div>
        <div class="card-body">
          <table class="table" id="result_list">
            <thead>
              <tr>
                <th scope="col" class="column">
                  <div class="text">#</div>
                  <div class="clear"></div>
                </th>
                <th scope="col" class="ortable">
                  <div class="text">Problem</div>
                  <div class="clear"></div>
                </th>
                <th scope="col">
                  <div class="text">Time</div>
                  <div class="clear"></div>
                </th>
                <th scope="col">
                  <div class="text">Status</div>
                  <div class="clear"></div>
                </th>
              </tr>
            </thead>
            <tbody>
              {% for attempt in attempts %}
              <tr>
                <td>
                  {{ attempt.id }}
                </td>
                <td>
                  {{ attempt.problem.title|safe }}
                </td>
                <td>
                  {{ attempt.created_at }}
                </td>
                <td>
                  {{ attempt.status|get_status }}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

codewar/templates/codewar/howto.html
{% load static %}
<div class="row">
  <div class="col-lg-12">
    <div class="card border-primary">
      <div class="card-header">
        <i class="fa fa-money"></i>
        <b>Problem</b>
      </div>
      <div class="card-body">
        <img style="width: 90%" src="/media/guide/guide_question.png" />
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="card border-primary">
      <div class="card-header">
        <i class="fa fa-paw"></i>
        <b>Editor</b>
      </div>
      <div class="card-body">
        <img style="width: 90%" src="/media/guide/guide_editor.png" />
      </div>
    </div>
  </div>
</div>

codewar/templates/codewar/menubar.html
{% if problem.published == False %}
  <span class="badge badge-pill badge-danger">
    <i class="icon-lock"></i>
  </span>
{% endif %}

<span class="badge badge-info float-right">
  <i class="icon-ghost"></i>
  {{ problem.get_type_display }}
</span>

{% if problem.required_score %}
<span class="badge badge-warning float-right d-md-down-none">
  <i class="icon-key"></i>
  {{ problem.required_score }}
</span>
{% endif %}

<span class="badge badge-danger float-right d-md-down-none">
  <i class="icon-shield"></i>
  {{ problem.get_real_score }}
</span>

{% if problem.penalty_score %}
  <span class="badge badge-warning float-right">
    <i class="icon-fire"></i>
    {{ problem.penalty_score }}
  </span>
{% endif %}

{% if problem.type == 0 %}
<span class="badge badge-success float-right d-md-down-none">
  <i class="icon-rocket"></i>
  {{ problem.count_testcase }}
</span>
{% endif %}

{% if problem.max_wrong %}
  <span class="badge badge-dark float-right">
    <i class="icon-clock"></i>
    {{ problem.max_wrong }}
  </span>
{% endif %}

{% if problem.max_attempts %}
  <span class="badge badge-warning float-right d-md-down-none">
    <i class="icon-graduation"></i>
    {{ problem.max_attempts }}
  </span>
{% endif %}

codewar/templates/codewar/problems.html
{% load codewartags %}
<div class="animated fadeIn">
  <div class="row">
    {% for problem in object_list %}
    <div class="col-lg-12">
      <div class="card border-primary">
        <div class="card-header" data-toggle="collapse" href="#" data-target="#collapse{{ problem.id }}" >
          {% comment %}
            <a data-toggle="collapse" href="#" data-target="#collapse{{ problem.id }}">
          {% endcomment %}
          <font color="{{ problem|get_colored_title:user }}">
            <b>{{ problem.event.prefix|get_event_prefix }} {{ problem.title }} - [{{ problem.user }}]</b>
          </font>
          {% comment %}
            </a>
          {% endcomment %}
          {% include "codewar/menubar.html" %}
        </div>
        <div class="card-body collapse in" id="collapse{{ problem.id }}">
          {{ problem|get_problem_content:user|safe }}
          <hr>
          {{ problem|get_button:user|safe }}
          {% include "codewar/problems/list-solved.html" %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% include "codewar/problems/show-problem.html" %}

codewar/templates/codewar/profile.html
{% load static %}
<div class="row">
  <div class="col-lg-8">
    <form id="formprofile" action="/codechallenges/profile/" method="post">
      {% csrf_token %}
      <div class="card">
        <div class="card-header">
          <strong>Basic info</strong>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="form-group col-lg-7">
              <label for="fullname">First Name</label>
              <input type="text" class="form-control" name="first_name" id="first_name" value="{{ user.first_name }}" placeholder="Enter your first name">
            </div>
            <div class="form-group col-lg-7">
              <label for="fullname">Last Name</label>
              <input type="text" class="form-control" name="last_name" id="last_name" value="{{ user.last_name }}" placeholder="Enter your last name">
            </div>
          </div>
        </div>
        <div class="card-footer">
          <a href="#formprofile" class="btn btn-primary"><i class="fa fa-dot-circle-o"></i> Submit</a>
        </div>
      </div>
    </form>
  </div>

  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <strong>Avatar</strong>
      </div>
      <div class="card-body">
        <form id="formavatar" action="/codechallenges/profile/" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <p>
              <img src="/media/img/avatar.png" width="150" height="150">
            </p>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

codewar/templates/codewar/topten.html
{% load static codewartags %}
<div class="tab-pane active" id="timeline" role="tabpanel" aria-expanded="true">
  {% for attempt in attempts %}
  <div class="callout callout-{% cycle "warning" "success" "info" "danger" "primary" %} m-0 py-3">
    <div>
      {{ attempt.title }}
    </div>
    <small class="text-muted mr-3">
      <i class="icon-calendar"></i>&nbsp;{{ attempt.datetime }}
    </small>
    <div>
      <small class="text-muted"><i class="icon-user"></i><a
          href="#codechallenges">&nbsp;{{ attempt.participant|get_full_name }}</a></small>
      <small class="text-muted">{{ attempt.score|show_score_admin:user|safe }}</small>
    </div>
  </div>
  <hr class="mx-3 my-0">
  {% endfor %}
</div>

<div class="tab-pane" id="top10" role="tabpanel" aria-expanded="false">
  {% for score in scores %}
    {% if forloop.counter0 == 0 %}
    <div class="callout callout-primary m-0 py-2 text-muted text-center bg-light text-uppercase">
      <small><b>Top 10</b></small>
    </div>
    {% endif %}
    {% if forloop.counter0 == 10 %}
    <div class="callout callout-danger m-0 py-2 text-muted text-center bg-light text-uppercase">
      <small><b>And Friends</b></small>
    </div>
    {% endif %}
    {% if forloop.counter0 < 10 %}
    <div class="callout callout-{% cycle "warning" "success" "info" "danger" "primary" %} m-0 py-3">
      <div class="avatar float-right">
        <img src="/media/img/avatar.png" class="img-avatar">
      </div>
      <div>
        <i class="icon-user"></i>
        <a href="#codechallenges">
          &nbsp;{{ score.participant|get_full_name }}
        </a>
      </div>
      <small class="text-muted"><i class="icon-chart"></i>&nbsp;{{ forloop.counter }}</small>
      <small class="text-muted mr-3">{{ score.score|show_score_admin:user|safe }}</small>
    </div>
    <hr class="mx-3 my-0">
    {% endif %}
  {% endfor %}
</div>